### ISSUE TITLE
一些没有时间的课（比如马原实践）会导致出错

### ISSUE THREAD

**Issue by qifang804** [WangZeKun/schedule_to_google#3]
![image](https://user-images.githubusercontent.com/15854722/64490688-36535580-d292-11e9-8515-310748502128.png)

**Comment by wzekin** [comment]
能给一下教务系统的截图吗
这个应该是时周数那栏出现了一些我没见过的格式，导致解析错误

**Comment by qifang804** [comment]
![image](https://user-images.githubusercontent.com/15854722/64521099-f5a71b00-d329-11e9-87d1-44ca0fcf75cb.png)

**Comment by wzekin** [comment]
跟这个没关系，上面那个只是一个warning，你可以忽略它，应该是有其他格式不正确的课程

**Comment by qifang804** [comment]
![image](https://user-images.githubusercontent.com/15854722/64531415-06fc2180-d342-11e9-88b9-2694cf9e8081.png)
![image](https://user-images.githubusercontent.com/15854722/64531422-0d8a9900-d342-11e9-9e10-84461b099ac3.png)

**Comment by qifang804** [comment]
可能是计算机系统基础实践出了问题？

**Comment by wzekin** [comment]
这个周上太nb了，我明天修，对了，顺便把issue提到 https://github.com/WangZeKun/bupt-api 这里，
这个先close了
